version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket s3-artifacts-bucket-610147131225 --region us-west-2
artifacts:
  files:
    - template.yaml
    - packaged.yaml
